---
# This playbook will create GCE instances

- name: Launch instances
  local_action:
    module: gce
    instance_names: "{{ names }}"
    machine_type: "{{ type }}"
    image: "{{ image }}"
    zone: "{{ zone }}"
  register: gce

- name: Wait for SSH to be available
  local_action:
    module: wait_for
    host: "{{ item.public_ip }}"
    port: 22
    delay: 10
    timeout: 60
    state: started
  with_items: gce.instance_data

- name: Add public ip to inventory for another tasks
  add_host: name={{ item.public_ip }} groups=wordpress-server
  with_items: gce.instance_data
